### ISSUE TITLE
systemd: ignoring selected units

### ISSUE THREAD

**Issue by jktjkt** [CESNET/velia#1]
There's this unit (`systemd-journal-upload.service`) whose state depends on an external service. We should not indicate a failure of the local box when a remote log server reboots or becomes unavailable, IMHO. Can you please add a startup option to the daemon which monitors systemd service state to ignore certain services altogether?

**Comment by peckato1** [comment]
Yes, this would be useful. I will work on it today.

**Comment by jktjkt** [comment]
fixed via https://github.com/CESNET/velia/commit/f2391d6c8d99414f67b13f53cc3289703638aa25, thanks
